### PR TITLE
Add IPv6 switch

### PR DESCRIPTION
**Pull request by ernestas-poskus**
Adding IPv6 switch which will control whether server should expect it.

### CODE REVIEW

**Comment by jamesjuran2** [comment]
For whatever it's worth, looks good to me!

**Comment by kyl191** [comment]
So the check is failing, I suspect the generated config file is having spacing issues. Now I'm wondering if CentOS6's init system in docker is suppressing the error.

In any case, I'm not too happy with the "We need to concatenate two variables together", the more straightforward solution is to have the protocol entirely configurable. I've created #25 which should resolve this. Take a look at it and see if it works for you? 

#21 is surprising - my understanding is that any recent kernel (2.6+) should have be able to create dualstacked sockets.

**Comment by ernestas-poskus** [comment]
> In any case, I'm not too happy with the "We need to concatenate two variables together", the more straightforward solution is to have the protocol entirely configurable. I've created #25 which should resolve this. Take a look at it and see if it works for you?

haven't tried it but I think using `openvpn_proto` default value `udp6` might brake https://github.com/kyl191/ansible-role-openvpn/blob/master/tasks/iptables.yml#L14 iptables.

Maybe let's introduce specific variable for openvpn server proto which would be constructed from `openvpn_proto` + 6 in defaults ?

**Comment by kyl191** [comment]
Moving discussion to #25

**Pull request closed without merging**
