### PR TITLE
Limit client key CN to 64 characters

### PR DESCRIPTION
**Pull request by rdeknijf**
X.509 CN has a max length of 64: https://tools.ietf.org/html/rfc5280#appendix-A.1

This fails my run on:
`problems making Certificate Request ... asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:158:maxsize=64`

### CODE REVIEW

**Comment by kyl191** [comment]
This will conflict with https://github.com/kyl191/ansible-role-openvpn/blob/master/templates/server.conf.j2#L68, breaking the cert check.

**Comment by rdeknijf** [comment]
Thanks! I didn't think to check. I'll fix all of them later today or tomorrow.

**Comment by rdeknijf** [comment]
And done.

I've also limited the CA and Server cert CNs to 64 chars. As you said, less important, but at least now this can never be a problem.

**Comment by kyl191** [comment]
LGTM, thanks!

**Pull request merged**
