### PR TITLE
Use ansible_os_family instead of testing distribution directly

### PR DESCRIPTION
**Pull request by archoversight**
This will catch the entire Red Hat "family" as it were rather than
limiting to just CentOS, thereby allowing this role to work against RHEL
8.

### CODE REVIEW

**Comment by dobbymoodge** [comment]
I think I remember now - `ansible_os_family` is set to `RedHat` for Fedora, and so the conditional in your PR is `True` for all versions of Fedora past `8`. The conditional I wrote gets the precision the playbook needs.

**Comment by archoversight** [comment]
@dobbymoodge with the downside that it doesn't work for RHEL systems... It sounds like Ansible considering Fedora RHEL family is what's broken here.

**Comment by dobbymoodge** [comment]
> @dobbymoodge with the downside that it **doesn't work for RHEL systems**... It sounds like Ansible considering Fedora RHEL family is what's broken here.

Um, I think the opposite? My PR is specifically to fix this properly for RHEL systems. Without my PR, the role fails on RHEL 8, which is my team's deployment platform. My change correctly specifies the version check for Fedora versions at or above 27, and CentOS and RHEL systems at or above 8.

**Comment by archoversight** [comment]
> > @dobbymoodge with the downside that it **doesn't work for RHEL systems**... It sounds like Ansible considering Fedora RHEL family is what's broken here.
> 
> Um, I think the opposite? My PR is specifically to fix this properly for RHEL systems. Without my PR, the role fails on RHEL 8, which is my team's deployment platform. My change correctly specifies the version check for Fedora versions at or above 27, and CentOS and RHEL systems at or above 8.

The check specifies `CentOS`, which is not the name used for `ansible_distribution` when the system is a RHEL 8 system, or so I assume. I'd have to go add a `debug` statement to verify.

This is the reason I created the PR in the first place because while deploying against a RHEL 8 system it failed to properly set the facts for setting the appropriate path.

**Comment by kyl191** [comment]
I merged #117 since that's closer to the intent of listing specific versions that we know are compatible.

My intent was more along the lines of "Fedora split openvpn configs into server and client, and CentOS followed". RHEL missing from that list was an oversight.

That said, I don't think the answer is to say "all RedHat type releases past 8 should used the systemd logic", since that isn't true.

It might be enough to say "if it's a RHEL-type, and using systemd, then use the systemd logic". I'm continuing that in #129, closing this for now.

**Pull request closed without merging**
