### PR TITLE
Remove typo 6 from server.conf proto config

### PR DESCRIPTION
**Pull request by ernestas-poskus**
With extra 6 openvpn wont start if TCP proto is used

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
cc @kyl191

**Comment by jamesjuran2** [comment]
I don't think that's a typo; I think that was done to make it use IPv6. Is IPv6 enabled on your system?

**Comment by ernestas-poskus** [comment]
@jamesjuran2 I run this on virtual machine where there is no support of IPv6 therefore using proto as `tcp` does not work.

**Comment by jamesjuran2** [comment]
IMHO the way to solve this would be to introduce a parameter controlling whether or not it should attempt to use IPv6.

**Comment by ernestas-poskus** [comment]
> IMHO the way to solve this would be to introduce a parameter controlling whether or not it should attempt to use IPv6.

sure why not https://github.com/kyl191/ansible-role-openvpn/pull/24

**Pull request closed without merging**
